# Generated by Django 3.2.6 on 2021-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
